extends:
  - airbnb
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:cypress/recommended
  - plugin:testing-library/recommended
  - plugin:jest-dom/recommended
  - prettier # must go last, to turn off some previous rules

plugins:
  - prefer-arrow
  - jest
  - jest-dom
  - testing-library
  - cypress

settings:
  react:
    version: latest

env:
  node: true
  browser: true
  jest: true

parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  no-unused-vars:
    - error
    - argsIgnorePattern: next
  require-await: error
  prefer-arrow-callback: error
  prefer-arrow/prefer-arrow-functions: error
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '**/*.test.js'
        - '**/*.spec.js'
        - '**/*test*'
        - '**/cypress/**'
  import/extensions: off
  react/forbid-prop-types: off
  react/react-in-jsx-scope: off
  react/prop-types: off
  react/jsx-filename-extension: off
  react/jsx-props-no-spreading: off

overrides:
  - files: [cypress/**/*.test.js]
    rules:
      'testing-library/await-async-query': off
